mainSections = ["post", "articles"]
rssFullContent = false

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar.avatar]
enabled = false

[article]
math = false
readingTime = true

[sidebar]
subtitle = "Navigating the Digital Realm"

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 50

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 50

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 50

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

[comments]
enabled = false
