module:
    hugoVersion:
        extended: true
        min: "0.87.0"

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: false
    favicon:

    footer:
        since:
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji:
        subtitle:
        avatar:
            enabled: false
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: false
        readingTime: true
        license:
            enabled: false
            default: None
            
    widgets:
        homepage: []
        page: []

    opengraph:
        twitter:
            site:
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true
